// utils/geminiService.js
const { GoogleGenerativeAI } = require("@google/generative-ai");
require("dotenv").config();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function generateEmail(eventType, data) {
  try {
    let prompt;

    if (eventType === "Offer Letter Notification") {
      prompt = `
You are an AI placement assistant who writes professional, motivational emails for college placement activities.
Your task is to create a formal, positive, and encouraging offer letter message.

### Data
Student Name: ${data.student_name}
Company Name: ${data.company_name}
Role: ${data.role}

### Requirements
- Formal and congratulatory tone.
- Include a message appreciating the student's achievement.
- Include a link to download the offer letter.
- Generate both a **Subject** line and an **HTML-formatted email body**.
`;
    } else {
      prompt = `
You are an AI assistant for the college placement cell.
Write short, professional, and encouraging email content based on the following context.

### Event Type
${eventType}

### Context Data
${JSON.stringify(data, null, 2)}

### Requirements
- Always include a **Subject** and an **HTML-formatted body**.
- Use professional tone, motivational language.
- Adjust tone based on event type (friendly for selection, formal for confirmation).
`;
    }

    // ✅ Use the correct Gemini model name
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    const result = await model.generateContent(prompt);

    // ✅ Handle response safely
    const response = result?.response?.text?.();
    if (!response) throw new Error("No text generated by Gemini.");

    // Split subject and body if Gemini returns them separately
    const subjectMatch = response.match(/Subject:\s*(.*)/i);
    const subject = subjectMatch ? subjectMatch[1].trim() : `Email - ${eventType}`;

    const bodyStart = response.indexOf("<");
    const html = bodyStart !== -1 ? response.slice(bodyStart) : `<p>${response}</p>`;

    return { subject, html };
  } catch (error) {
    console.error("[geminiService] Error generating email:", error);
    throw new Error("Failed to generate email content");
  }
}

module.exports = { generateEmail };
